#!/usr/bin/env bash
# Admin-side tool (run on the CENTRAL machine): joins an ALREADY-RUNNING remote
# office peer to the channel, using ONLY this machine's own retained org admin
# identity — nothing is distributed to the office (see docs/adr/0011). Use this
# when the office's join package was made with `INCLUDE_ADMIN_MSP=false`
# (pack-join.sh); with the default INCLUDE_ADMIN_MSP=true, office-node joins
# itself on first `start` and this script is not needed.
#
# Requires: the target office already ran `office-node join` + `office-node
# start` and its peer port is reachable from here (same LAN/VPN, firewall
# allowing the peer port — see MULTI-HOST-LAB.md for cross-machine networking).
#
#   cd network && bash tools/office-node/remote-join.sh peer4 192.168.1.50:9061
set -euo pipefail

PEER_ID="${1:?usage: remote-join.sh <peer-id> <office-host:port>}"
PEER_ADDR="${2:?usage: remote-join.sh <peer-id> <office-host:port>}"

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NETWORK_DIR="$(cd "${SCRIPT_DIR}/../.." && pwd)"
SAMPLES_DIR="${NETWORK_DIR}/vendor/fabric-samples"
TESTNET_DIR="${SAMPLES_DIR}/test-network"
ORGS_DIR="${TESTNET_DIR}/organizations"
PEER_FQDN="${PEER_ID}.org2.example.com"
PEER_HOME="${ORGS_DIR}/peerOrganizations/org2.example.com/peers/${PEER_FQDN}"
GENESIS="${TESTNET_DIR}/channel-artifacts/ledgerchannel.block"

[ -d "${PEER_HOME}" ] || { echo "!! ${PEER_HOME} not found — was this peer-id minted by pack-join.sh on this machine?"; exit 1; }
[ -f "${GENESIS}" ] || { echo "!! ${GENESIS} not found — run network/bootstrap.sh first"; exit 1; }

export PATH="${SAMPLES_DIR}/bin:${PATH}"
# The office's own TLS root CA (generated by pack-join.sh when it minted this
# peer's identity — already on this machine, never needs to be sent back here)
# verifies the far end really is that peer; this machine's own admin identity
# is what proves to THAT peer that the join request is authorized.
export CORE_PEER_TLS_ENABLED=true
export CORE_PEER_TLS_ROOTCERT_FILE="${PEER_HOME}/tls/ca.crt"
export CORE_PEER_LOCALMSPID=Org2MSP
export CORE_PEER_MSPCONFIGPATH="${ORGS_DIR}/peerOrganizations/org2.example.com/users/Admin@org2.example.com/msp"
export CORE_PEER_ADDRESS="${PEER_ADDR}"
export FABRIC_CFG_PATH="${TESTNET_DIR}/compose/docker/peercfg"

echo ">> joining ${PEER_FQDN} (at ${PEER_ADDR}) to ledgerchannel, using this machine's own admin identity"
peer channel join -b "${GENESIS}"
echo ">> done — the office's own \`office-node status\` should now show it catching up"
